---
galaxy_info:
  author: Jason L. Shiffer <jshiffer AT zerotao DOT org>
  description: Ansible Role to install packages
  license: BSD
  min_ansible_version: 1.2
  platforms:
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  categories:
    - packaging
dependencies: []
