---
- name: Debian | install packages
  apt:
   cache_valid_time={{ item.cache_valid_time |default(omit) }}
   deb={{ item.deb |default(omit)}}
   default_release={{ item.default_release |default(omit) }}
   dpkg_options={{ item.dpkg_options |default(omit) }}
   force={{ item.force |default(omit) }}
   install_recommends={{ item.install_recommends |default(omit) }}
   name={{ item.name }}
   purge={{ item.purge |default(omit) }}
   state={{ item.state |default(omit) }}
   update_cache={{ item.update_cache |default(omit) }}
   upgrade={{ item.upgrade |default(omit) }}
  with_items: "{{ packages | default([]) }}"
